### PR TITLE
Updated Debian packaging to fix lintian warnings and errors.

### PR DESCRIPTION
**Pull request by flexiondotorg**
Hi Chris,

I'm a Debian maintainer and lead for Ubuntu MATE. I am keen to see `hal-flash` make it into the official archives :-) I've updated the Debian packaging to fix the `lintian` warnings and errors. I've built and tested the 0.3.1 package on:

  * Ubuntu 12.04
  * Ubuntu 14.04
  * Ubuntu 14.10
  * Ubuntu 15.04
  * Ubuntu 15.10

If you would be good enough to accept this merge than hopefully I can get `hal-flash` sponsored for upload to the official archives.

Regards, Martin.

### CODE REVIEW

**Comment by cshorler** [comment]
On 19 May 2015 18:46:11 BST, Martin Wimpress <notifications@github.com> wrote:
>Hi Chris,
>
>I'm a Debian maintainer and lead for Ubuntu MATE. I am keen to see
>`hal-flash` make it into the official archives :-) I've updated the
>Debian packaging to fix the `lintian` warnings and errors. I've built
>and tested the 0.3.1 package on:
>
>  * Ubuntu 12.04
>  * Ubuntu 14.04
>  * Ubuntu 14.10
>  * Ubuntu 15.04
>  * Ubuntu 15.10
>
>If you would be good enough to accept this merge than hopefully I can
>get `hal-flash` sponsored for upload to the official archives.
>
>Regards, Martin.

Looks good, will accept tonight after work.  I've experienced an issue getting it integrated with SUSE - the package name (if interested I think it's in the SUSE factory archives).  

Also, it conflicts / doesn't work with the wrapper for using chrome flash in Firefox - would be worth adding this to the package info / conflicts.

Chris

**Comment by chadmiller** [comment]
Martin, in the Ubuntu world (not necessarily in Debian), the new flash package is "adobe-flashplugin" in the partners repo. You might want to consider it in you package relationships too.

**Comment by cshorler** [comment]
@chadmiller I just tweaked it, I assume you're referring to Suggests:?   (flexiondotorg-master branch)
If this is good I'll merge it.

**Comment by chadmiller** [comment]
Oh, you may not even want that Suggests. I think I read the wrong thing when commenting. The suggests doesn't hurt, and it may be helpful. It's up to you.

**Comment by cshorler** [comment]
decided to merge without the additional commit

**Pull request merged**
